name: "Test"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - run: npm run lint

      - run: npm test
